title:            "Katherine Huang"
description:      "I'm a student passionate about conducting, communicating, and applying scientific research. I've interned at Harvard University and help organize MAHacks, a high school hackathon in Boston."
url:              http://katherinehuang.co # no slash at the end

links:
  - name: About
    url: /about
  - name: Writing
    url: /posts
  - name: Resume
    url: /Katherine-Huang-Resume.pdf

permalink: /posts/:title

defaults:
  - values:
      layout: "default"